apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvnweb-demo-<BUILD_TAG>
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mvnweb-demo-<BUILD_TAG>
  template:
    metadata:
      labels:
        app: mvnweb-demo-<BUILD_TAG>
    spec:
      containers:
      - name: mvnweb-demo-<BUILD_TAG>
        image: registry.cn-beijing.aliyuncs.com/dengyou/mvnweb-demo:<BUILD_TAG>
        imagePullPolicy: IfNotPresent

